apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversao-temperatura
spec:
  replicas: 1
  selector:
    matchlabels:
      app: conversao-temperatura
  template:
    metadata:
      labels:
        app: conversao-temperatura
    spec:
      containers:
        - name: conversao-temperatura
          image: felipejnsouza/conversao-temperatura:v1
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: conversao-temperatura
spec:
  selector:
    app: conversao-temperatura
  ports:
  - protocol: TCP
    port: 80
    nodePort: 30000
  type: NodePort